//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kampiraliste
{
    using System;
    using System.Collections.Generic;
    
    public partial class gost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gost()
        {
            this.racuns = new HashSet<racun>();
            this.prijavas = new HashSet<prijava>();
        }
    
        public int id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string spol { get; set; }
        public System.DateTime datum_rodenja { get; set; }
        public string drzava_id_rodenja { get; set; }
        public string drzava_id_drzavljanstvo { get; set; }
        public int dokument_id { get; set; }
        public string broj_dokumenta { get; set; }
    
        public virtual drzava drzava { get; set; }
        public virtual drzava drzava1 { get; set; }
        public virtual vrsta_dokumenta vrsta_dokumenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<racun> racuns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prijava> prijavas { get; set; }
    }
}
