//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kampiraliste
{
    using System;
    using System.Collections.Generic;
    
    public partial class prijava
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prijava()
        {
            this.racuns = new HashSet<racun>();
        }
    
        public int id { get; set; }
        public int gost_id { get; set; }
        public int smjestaj_id { get; set; }
        public System.DateTime datum_prijave { get; set; }
        public System.DateTime datum_odjave { get; set; }
        public int zaposlenik_id { get; set; }
        public int status_osobe_id { get; set; }
        public string organizacija_dolaska { get; set; }
    
        public virtual smjestaj smjestaj { get; set; }
        public virtual zaposlenik zaposlenik { get; set; }
        public virtual gost gost1 { get; set; }
        public virtual status_osobe status_osobe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<racun> racuns { get; set; }

        public override string ToString()
        {
            return gost1.ime + " " + gost1.prezime + " => " + this.datum_prijave.ToString("yyyy-MM-dd") + " - " + this.datum_odjave.ToString("yyyy-MM-dd");
        }
    }
}
