//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kampiraliste
{
    using System;
    using System.Collections.Generic;
    
    public partial class prijava
    {
        public int id { get; set; }
        public int gost_id { get; set; }
        public int smjestaj_id { get; set; }
        public System.DateTime datum_prijave { get; set; }
        public System.DateTime datum_odjave { get; set; }
        public int zaposlenik_id { get; set; }
        public int status_osobe_id { get; set; }
        public string organizacija_dolaska { get; set; }
    
        public virtual smjestaj smjestaj { get; set; }
        public virtual zaposlenik zaposlenik { get; set; }
        public virtual gost gost1 { get; set; }
        public virtual status_osobe status_osobe { get; set; }
    }
}
